# Generated by Django 3.2.12 on 2022-03-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=128)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.CharField(max_length=254, null=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=254, null=True)),
                ('date_updated', models.DateTimeField()),
                ('is_staff', models.IntegerField()),
                ('patient_id', models.CharField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
    ]
