# Generated by Django 3.2.12 on 2022-03-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=254, null=True)),
                ('gender', models.CharField(max_length=128, null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('second_name', models.CharField(max_length=150, null=True)),
                ('surname', models.CharField(max_length=150, null=True)),
                ('date_updated', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(null=True)),
                ('voided', models.CharField(max_length=254, null=True)),
            ],
        ),
    ]
