# Generated by Django 3.2.12 on 2022-03-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='county',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='identifier',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='village',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
