# Generated by Django 3.2.12 on 2022-03-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220303_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='identifier',
            new_name='ccc_number',
        ),
    ]
