# Generated by Django 3.2.12 on 2022-03-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_identifier_patient_ccc_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, null=True)),
                ('mfl_code', models.CharField(max_length=128, null=True)),
                ('facility_type', models.CharField(max_length=150, null=True)),
                ('county', models.DateTimeField(blank=True, null=True)),
                ('sub_county', models.CharField(max_length=150, null=True)),
                ('ward', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
