# Generated by Django 3.2.12 on 2022-03-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220304_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='National_id',
            new_name='national_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
    ]
