# Generated by Django 3.2.12 on 2022-03-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220304_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mfl_code',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
