# Generated by Django 3.2.12 on 2022-03-25 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_registry', '0003_auto_20220325_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
